# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 517b58d76adc7d4fe25b32422401b2c8688dca842b208112b3a5c623798be4604840b3d197f67f8c2f4d16fed482e913d94d4369dcf1f37f615043bbcaa9bb75

test:
  secret_key_base: 1a43b4095a1f9a643120b2ab92896f40e844938ef3792b35209a51a0aa6a1fe294637164f08df045871084ac6459aaa2f988e122bbd2595b0ccbe4707e9979ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
